// Auto-generated by deploy.py - DO NOT EDIT MANUALLY
const SOTERIA_CONFIG = {
    APP_ID: 749658795,
    APP_ADDRESS: "GWWCEG6OYN2Q7R4G2LHKWC3KNQA44RTYCZA5ROPR2KHEEGJ3HT6NZOMRZE",
    NETWORK: "testnet",
    ALGOD_SERVER: "https://testnet-api.algonode.cloud",
    INDEXER_SERVER: "https://testnet-idx.algonode.cloud"
};

// For browser compatibility
if (typeof module !== 'undefined' && module.exports) {
    module.exports = SOTERIA_CONFIG;
}
