#!/usr/bin/env python3
"""
Soteria Smart Contract Deployment Script
Deploys the contract to Algorand TestNet and saves the App ID
"""

import json
import os
from algosdk import account, mnemonic
from algosdk.v2client import algod
from algosdk.transaction import ApplicationCreateTxn, OnComplete, StateSchema
from algosdk.logic import get_application_address
import base64

# Algorand TestNet Configuration
ALGOD_ADDRESS = "https://testnet-api.algonode.cloud"
ALGOD_TOKEN = ""

def load_teal_files():
    """Load the compiled TEAL files"""
    artifacts_dir = "smartContract/artifacts"
    
    with open(f"{artifacts_dir}/approval.teal", "r") as f:
        approval_program = f.read()
    
    with open(f"{artifacts_dir}/clear.teal", "r") as f:
        clear_program = f.read()
    
    return approval_program, clear_program

def compile_program(client, source_code):
    """Compile TEAL source code"""
    compile_response = client.compile(source_code)
    return base64.b64decode(compile_response['result'])

def create_app(client, private_key, approval_program, clear_program):
    """Deploy the smart contract"""
    
    # Decode private key
    sender = account.address_from_private_key(private_key)
    
    print(f"Deploying from account: {sender}")
    
    # Get suggested parameters
    params = client.suggested_params()
    
    # Compile programs
    print("Compiling approval program...")
    approval_program_compiled = compile_program(client, approval_program)
    
    print("Compiling clear program...")
    clear_program_compiled = compile_program(client, clear_program)
    
    # Define schema
    # Global state: we don't need any (boxes handle storage)
    global_schema = StateSchema(num_uints=0, num_byte_slices=0)
    # Local state: not used
    local_schema = StateSchema(num_uints=0, num_byte_slices=0)
    
    # Create transaction
    txn = ApplicationCreateTxn(
        sender=sender,
        sp=params,
        on_complete=OnComplete.NoOpOC,
        approval_program=approval_program_compiled,
        clear_program=clear_program_compiled,
        global_schema=global_schema,
        local_schema=local_schema,
        extra_pages=0  # We don't need extra pages
    )
    
    # Sign transaction
    signed_txn = txn.sign(private_key)
    
    # Submit transaction
    print("Submitting transaction...")
    tx_id = client.send_transaction(signed_txn)
    print(f"Transaction ID: {tx_id}")
    
    # Wait for confirmation
    print("Waiting for confirmation...")
    confirmed_txn = wait_for_confirmation(client, tx_id, 4)
    
    # Get app ID
    app_id = confirmed_txn['application-index']
    app_address = get_application_address(app_id)
    
    print("\n" + "="*60)
    print("✅ CONTRACT DEPLOYED SUCCESSFULLY!")
    print("="*60)
    print(f"App ID: {app_id}")
    print(f"App Address: {app_address}")
    print("="*60)
    
    return app_id, app_address

def wait_for_confirmation(client, txid, timeout):
    """Wait for transaction confirmation"""
    start_round = client.status()["last-round"] + 1
    current_round = start_round

    while current_round < start_round + timeout:
        try:
            pending_txn = client.pending_transaction_info(txid)
        except Exception:
            return None
        if pending_txn.get("confirmed-round", 0) > 0:
            return pending_txn
        elif pending_txn["pool-error"]:
            raise Exception(f'Pool error: {pending_txn["pool-error"]}')
        client.status_after_block(current_round)
        current_round += 1
    raise Exception(f"Transaction {txid} not confirmed after {timeout} rounds")

def save_config(app_id, app_address):
    """Save deployment config to files"""
    
    config = {
        "app_id": app_id,
        "app_address": app_address,
        "network": "testnet",
        "deployed_at": __import__('datetime').datetime.now().isoformat()
    }
    
    # Save to smartContract/config.json
    with open("smartContract/config.json", "w") as f:
        json.dump(config, f, indent=2)
    print("✅ Saved to smartContract/config.json")
    
    # Save to frontend/config.js
    frontend_config = f"""// Auto-generated by deploy.py - DO NOT EDIT MANUALLY
const SOTERIA_CONFIG = {{
    APP_ID: {app_id},
    APP_ADDRESS: "{app_address}",
    NETWORK: "testnet",
    ALGOD_SERVER: "https://testnet-api.algonode.cloud",
    INDEXER_SERVER: "https://testnet-idx.algonode.cloud"
}};

// For browser compatibility
if (typeof module !== 'undefined' && module.exports) {{
    module.exports = SOTERIA_CONFIG;
}}
"""
    with open("frontend/config.js", "w") as f:
        f.write(frontend_config)
    print("✅ Saved to frontend/config.js")
    
    # Save to backend/resources/algorand.properties
    os.makedirs("backend/resources", exist_ok=True)
    backend_config = f"""# Auto-generated by deploy.py - DO NOT EDIT MANUALLY
algorand.app.id={app_id}
algorand.app.address={app_address}
algorand.network=testnet
algorand.algod.address=https://testnet-api.algonode.cloud
algorand.indexer.address=https://testnet-idx.algonode.cloud
"""
    with open("backend/resources/algorand.properties", "w") as f:
        f.write(backend_config)
    print("✅ Saved to backend/resources/algorand.properties")

def main():
    print("="*60)
    print("SOTERIA SMART CONTRACT DEPLOYMENT")
    print("="*60)
    print()
    
    # Check if TEAL files exist
    if not os.path.exists("smartContract/artifacts/approval.teal"):
        print("❌ Error: Compiled TEAL files not found!")
        print("Please run: python smartContract/contract.py")
        return
    
    # Get deployer account
    print("Choose deployment account option:")
    print("  1. Generate new test account (RECOMMENDED)")
    print("  2. Use existing 25-word Algorand mnemonic")
    print()
    print("Note: Pera Wallet uses 24-word mnemonics which require conversion.")
    print("      For simplicity, use option 1 to generate a test account.")
    print()
    choice = input("Enter choice (1 or 2): ").strip()
    
    if choice == "1" or choice == "":
        # Generate new account
        print("\n" + "="*60)
        print("GENERATING NEW ACCOUNT")
        print("="*60)
        private_key, sender = account.generate_account()
        mnemonic_phrase = mnemonic.from_private_key(private_key)
        
        print(f"\n✅ Account generated!")
        print(f"Address: {sender}")
        print(f"\n⚠️  SAVE THESE CREDENTIALS SECURELY:")
        print("="*60)
        print("Mnemonic (25 words):")
        print(mnemonic_phrase)
        print("="*60)
        
        # Save to file for convenience (WARNING: THIS IS INSECURE FOR PRODUCTION)
        with open("deployer_account.txt", "w") as f:
            f.write(f"DEPLOYER ACCOUNT (TestNet Only - DO NOT USE FOR MAINNET)\n")
            f.write(f"="*60 + "\n")
            f.write(f"Address: {sender}\n")
            f.write(f"Mnemonic: {mnemonic_phrase}\n")
            f.write(f"="*60 + "\n")
            f.write(f"\nWARNING: Delete this file after deployment!\n")
        
        print(f"\n💾 Credentials saved to: deployer_account.txt")
        print("   ⚠️  DELETE THIS FILE AFTER DEPLOYMENT!")
        
        print(f"\n⚠️  FUND THIS ADDRESS WITH TESTNET ALGO:")
        print("   1. Go to: https://bank.testnet.algorand.network/")
        print(f"   2. Paste address: {sender}")
        print("   3. Click 'Dispense'")
        print("   4. Wait ~5 seconds for confirmation")
        print()
        input("Press Enter after funding the account...")
        
    else:
        # Use existing 25-word mnemonic
        print("\nEnter your 25-word Algorand mnemonic:")
        print("⚠️  This account will be the contract owner/creator")
        print()
        mnemonic_phrase = input("Mnemonic: ").strip()
        
        try:
            private_key = mnemonic.to_private_key(mnemonic_phrase)
            sender = account.address_from_private_key(private_key)
            print(f"\n✅ Account loaded: {sender}")
        except Exception as e:
            print(f"\n❌ Invalid mnemonic: {e}")
            print("\nNote: Only 25-word Algorand mnemonics are supported.")
            print("Pera Wallet uses 24-word BIP39 mnemonics.")
            print("Please use option 1 to generate a new account.")
            return
    
    # Initialize Algod client
    client = algod.AlgodClient(ALGOD_TOKEN, ALGOD_ADDRESS)
    
    # Check account balance
    try:
        account_info = client.account_info(sender)
        balance = account_info.get('amount', 0) / 1_000_000  # Convert to ALGO
        print(f"Account balance: {balance} ALGO")
        
        if balance < 0.5:
            print("\n⚠️  WARNING: Low balance!")
            print("You need at least 0.5 ALGO to deploy the contract.")
            print("Fund your account at: https://bank.testnet.algorand.network/")
            response = input("\nContinue anyway? (yes/no): ")
            if response.lower() != 'yes':
                return
    except Exception as e:
        print(f"⚠️  Could not check balance: {e}")
    
    # Load TEAL files
    print("\nLoading TEAL files...")
    approval_program, clear_program = load_teal_files()
    
    # Deploy
    print("\n" + "="*60)
    print("DEPLOYING CONTRACT...")
    print("="*60 + "\n")
    
    try:
        app_id, app_address = create_app(client, private_key, approval_program, clear_program)
        
        # Save configuration
        print("\nSaving configuration files...")
        save_config(app_id, app_address)
        
        print("\n" + "="*60)
        print("NEXT STEPS:")
        print("="*60)
        print("1. Fund the app address with ALGO for box storage:")
        print(f"   Address: {app_address}")
        print("   Amount: At least 1 ALGO (for box creation)")
        print()
        print("2. Restart your backend and frontend to load the new config")
        print()
        print("3. Update script.js if needed (should auto-load from config.js)")
        print()
        print("4. Test creating a guest key!")
        print("="*60)
        
    except Exception as e:
        print(f"\n❌ Deployment failed: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main()